language: python
python:
  - "2.7"
  - "3.4"
install: "pip install -r test-requirements.txt"
script: tox -e pep8
notifications:
  email:
    recipients:
      - ntk148v@gmail.com 
      - ducbac230895@gmail.com
    on_success: change
    on_failure: always